import { AlertTriangle } from "lucide-react";

export function DisclaimerBanner() {
  return (
    <div className="flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4">
      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
      <p className="text-sm text-amber-800">
        This analysis is generated by AI and does not constitute legal advice.
        All conclusions should be reviewed and verified by qualified legal
        professionals before reliance.
      </p>
    </div>
  );
}
